### ISSUE TITLE
failure to find trainres.json

### ISSUE THREAD

**Issue by Redeeman** [trougnouf/nind-denoise#9]
```
cs and/or ucs not set, using defaults ...
Warning: cs and ucs not known for this architecture; values may be sub-optimal
cs=512, ucs=448
find_best did not find 2019-02-18T20:10_run_nn.py_--time_limit_259200_--batch_size_94_--test_reserve_ursulines-red_stefantiek_ursulines-building_MuseeL-Bobo_CourtineDeVillersDebris_MuseeL-Bobo-C500D_--skip_sizecheck_--lr_3e-4/trainres.json

```
is it possible you could provide trainres.json?

**Comment by trougnouf** [comment]
Hi Redeeman,
What command did you run when you got this error?
Here is trainres.json for this model: 
[trainres.json](https://github.com/trougnouf/nind-denoise/files/15261706/trainres.json)

**Comment by domnakus** [comment]
Hi,
I'm encountering similar issues.
Are you sure the json is properly formatted? If I try to use it I get a key-error:

```
Traceback (most recent call last):
  File "/home/domnakus/Documents/denoise/nind-denoise/src/nind_denoise/denoise_image.py", line 227, in <module>
    model = Model.instantiate_model(network=args.g_network, model_path=args.model_path,
                                    strparameters=args.model_parameters, keyword='generator',
                                    device=device, models_dpath=args.models_dpath)
  File "/home/domnakus/Documents/denoise/nind-denoise/src/nind_denoise/nn_common.py", line 127, in instantiate_model
    path = Model.complete_path(path=model_path, keyword=keyword, models_dpath=models_dpath)
  File "/home/domnakus/Documents/denoise/nind-denoise/src/nind_denoise/nn_common.py", line 107, in complete_path
    best_model_path = find_best(path, model_t=keyword)
  File "/home/domnakus/Documents/denoise/nind-denoise/src/nind_denoise/nn_common.py", line 100, in find_best
    best_epoch = res['best_epoch']['validation_loss']
                 ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'validation_loss'
```

**Comment by trougnouf** [comment]
> Hi, I'm encountering similar issues. Are you sure the json is properly formatted? If I try to use it I get a key-error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/domnakus/Documents/denoise/nind-denoise/src/nind_denoise/denoise_image.py", line 227, in <module>
>     model = Model.instantiate_model(network=args.g_network, model_path=args.model_path,
>                                     strparameters=args.model_parameters, keyword='generator',
>                                     device=device, models_dpath=args.models_dpath)
>   File "/home/domnakus/Documents/denoise/nind-denoise/src/nind_denoise/nn_common.py", line 127, in instantiate_model
>     path = Model.complete_path(path=model_path, keyword=keyword, models_dpath=models_dpath)
>   File "/home/domnakus/Documents/denoise/nind-denoise/src/nind_denoise/nn_common.py", line 107, in complete_path
>     best_model_path = find_best(path, model_t=keyword)
>   File "/home/domnakus/Documents/denoise/nind-denoise/src/nind_denoise/nn_common.py", line 100, in find_best
>     best_epoch = res['best_epoch']['validation_loss']
>                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
> KeyError: 'validation_loss'
> ```

Please provide the command you used to run this model and the model you are trying to run.

For example the following runs with no issue on my machine with a fresh clone: `python3 denoise_image.py --network UNet --model_path ../../models/nind_denoise/2019-08-03T16\:14_nn_train.py_--g_network_UNet_--weight_SSIM_1_--batch_size_65_--test_reserve_ursulines-red_stefantiek_ursulines-building_MuseeL-Bobo_CourtineDeVillersDebris_MuseeL-Bobo-C500D_--train_data_datasets-train-NIND_128_96_--g_model_path_models-20/generator_280.pt --input '/orb/Pictures/Doodles/sampleimage.jpg' -o /home/trougnouf/tmp/out.jpg`

**Comment by domnakus** [comment]
I used the example from your README.md. But the way you did it also worked for me, thanks!
